# Generated by Django 5.1.1 on 2025-03-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('JINS', 'Jins'), ('AYOL', 'Ayol'), ('ERKAK', 'Erkak')], default='JINS', max_length=10, null=True),
        ),
    ]
