# Generated by Django 5.1.1 on 2025-03-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_id_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('JINS', 'Jins'), ('AYOL', 'Ayol'), ('ERKAK', 'Erkak')], default='JINS', max_length=10),
        ),
    ]
