# Generated by Django 5.1.1 on 2025-03-14 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_view_content_alter_view_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='content.content'),
        ),
    ]
