# Generated by Django 5.1.1 on 2025-03-18 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_view_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='like',
            new_name='video',
        ),
    ]
