# Generated by Django 5.1.1 on 2025-04-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_commentlike_commentreply_playlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='user',
            new_name='author',
        ),
    ]
