# Generated by Django 5.1.1 on 2025-04-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_rename_user_playlist_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='author',
            new_name='user',
        ),
    ]
