# Generated by Django 5.1.1 on 2025-04-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chanel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
